name: layout
description: >
  Sample app from "Building Layouts", https://flutter.io/docs/development/ui/layout.
version: 1.0.0

environment:
  sdk: '>=2.0.0-dev.68.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flame: ^0.22.1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/covigotchi/healthy.png
    - assets/images/covigotchi/deadAnim/dead1.png
    - assets/images/covigotchi/deadAnim/dead2.png
    - assets/images/covigotchi/deadAnim/dead3.png
    - assets/images/covigotchi/GrammasHouseFinal.png
    - assets/images/covigotchi/sick1.png
    - assets/images/covigotchi/sick2.png
    - assets/images/StatefulHouse/GrammasHealthy.png
    - assets/images/StatefulHouse/sickhouse.png
    - assets/images/StatefulHouse/sickhouse2.png
    - assets/images/StatefulHouse/deadhouse2.png
    - assets/images/sprites/groceryBag.png
    - assets/images/sprites/medBottle.png
    - assets/images/sprites/n85Mask.png
    - assets/images/CovaGotchi.png
